import {
  describe,
  expect,
  it,
} from 'vitest';

import { DEFAULT_ANSWERS } from '../answers/answers';

import { astro } from './astro';

import type {
  Answers,
  HostedFramework,
  Library,
} from '../answers/answers';

const answersFor = (overrides: Partial<Answers> = {}): Answers => {
  return { ...DEFAULT_ANSWERS, target: 'astro', ...overrides };
};

const recordFor = (overrides: Partial<Answers> = {}) => {
  return astro(answersFor(overrides));
};

describe('scaffold', () => {
  it('writes the exact argv for the default answers', () => {
    expect(recordFor().scaffold('demo-site', DEFAULT_ANSWERS)).toEqual({
      kind: 'create',
      args: [
        'astro@latest', 'demo-site',
        '--template', 'minimal',
        '--no-install',
        '--no-git',
        '--no-ai',
        '--skip-houston',
        '--yes',
      ],
    });
  });
});

describe('the build it owns', () => {
  /**
   * Astro is a Vite application, but its Vite options belong in `astro.config.mjs`; a `vite.config.ts` beside that
   * would be read by nothing, which is why the test run borrows the resolved config through `getViteConfig` instead.
   */
  it('owns no vite config and borrows the resolved one for tests', () => {
    const record = recordFor();

    expect(record.vite).toBe(false);
    expect(record.vitePlugin).toEqual({ imports: [], calls: [] });
    expect(record.vitestFactory?.call).toBe('getViteConfig');
    // The second import is what makes `test` a legal key; `astro check` rejects the config without it.
    expect(record.vitestFactory?.imports).toEqual([
      "import { getViteConfig } from 'astro/config';",
      "import 'vitest/config';",
    ]);
  });

  // `astro check` is the only thing that types a template, and the types it reads are generated by `astro sync`.
  it('gates on astro check, after a sync', () => {
    const record = recordFor();

    expect(record.typecheck).toBe('astro sync && astro check');
    expect(record.build).toBe('astro build');
    expect(record.prepare).toBe('astro sync');
  });

  // A package subpath the framework ships, not a generated file.
  it('extends the tsconfig astro publishes, and names the generated types', () => {
    const record = recordFor();

    expect(record.tsconfig.extends).toBe('astro/tsconfigs/strict');
    expect(record.tsconfig.include).toContain('.astro/types.d.ts');
    expect(record.tsconfig.include).toContain('**/*.astro');
  });

  // `.astro` is not `.html`: the html layer's parser cannot read a template's frontmatter fence.
  it('asks for the astro layer and not the html one', () => {
    expect(recordFor().astro).toBe(true);
    expect(recordFor().html).toBe(false);
  });
});

describe('the hosted framework axis', () => {
  it('hosts nothing by default, and is still a complete target', () => {
    const record = recordFor();

    expect(record.hostsFramework).toBe(true);
    expect(record.framework).toBeUndefined();
    expect(record.stateRules).toEqual([]);
    expect(record.dependencies).toBeUndefined();
    // The template component rule stands on its own, with no framework extension beside it.
    expect(record.naming['src/**/*.astro']).toBe('!([a-z]*[A-Z]*)');
  });

  it.each<[HostedFramework, string, string]>([
    ['react', 'src/**/*.tsx', '@astrojs/react'],
    ['vue', 'src/**/*.vue', '@astrojs/vue'],
    ['svelte', 'src/**/*.svelte', '@astrojs/svelte'],
    ['solid', 'src/**/*.tsx', '@astrojs/solid-js'],
  ])('composes %s as an island', (hostedFramework, componentGlob, integration) => {
    const record = recordFor({ hostedFramework });

    expect(record.framework).toBe(hostedFramework);
    expect(record.devDependencies).toContain(integration);
    // Both rules: a template is still a component, and so is the island beside it.
    expect(record.naming['src/**/*.astro']).toBe('!([a-z]*[A-Z]*)');
    expect(record.naming[componentGlob]).toBe('!([a-z]*[A-Z]*)');
  });

  it('brings the framework itself and its testing library', () => {
    const record = recordFor({ hostedFramework: 'vue' });

    expect(record.dependencies).toEqual(['vue']);
    expect(record.testDevDependencies).toEqual(['@vue/test-utils']);
    expect(record.stateRules).toEqual(['vue-reactivity.md']);
  });

  /**
   * `jsx` stays Astro's `preserve`, which is what makes a template readable as JSX. Only Solid adds an import source:
   * `@types/react` already answers for React, and the two single-file-component frameworks have no JSX to type.
   */
  it('adds a jsx import source only where the framework needs one', () => {
    expect(recordFor({ hostedFramework: 'solid' }).tsconfig.jsxImportSource).toBe('solid-js');
    expect(recordFor({ hostedFramework: 'react' }).tsconfig.jsxImportSource).toBeUndefined();
    expect(recordFor().tsconfig.jsx).toBeUndefined();
  });

  // The lint layer loads both, whether or not the site hosts a framework.
  it('installs astro, its checker and the two packages the lint layer loads', () => {
    const record = recordFor();

    expect(record.devDependencies).toContain('astro');
    expect(record.devDependencies).toContain('@astrojs/check');
    expect(record.devDependencies).toContain('eslint-plugin-astro');
    expect(record.devDependencies).toContain('astro-eslint-parser');
  });

  // Found by an install that aborted: pnpm refuses esbuild's script unless the project allows it by name.
  it('allows the build script astro cannot install without', () => {
    expect(recordFor().allowBuilds).toContain('esbuild');
  });

  // Tailwind reaches an Astro build as a Vite plugin, so the project installs that rather than an integration.
  it('installs the tailwind vite plugin when tailwind was answered', () => {
    const libraries: Library[] = ['tailwind'];

    expect(recordFor({ libraries }).devDependencies).toContain('@tailwindcss/vite');
    expect(recordFor().devDependencies).not.toContain('@tailwindcss/vite');
  });
});
